// Code generated by "stringer -type=MType"; DO NOT EDIT.

package bt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Choke-0]
	_ = x[Unchoke-1]
	_ = x[Interested-2]
	_ = x[NotInterested-3]
	_ = x[Have-4]
	_ = x[Bitfield-5]
	_ = x[Request-6]
	_ = x[Piece-7]
	_ = x[Cancel-8]
	_ = x[Port-9]
	_ = x[KeepAlive-10]
}

const _MType_name = "ChokeUnchokeInterestedNotInterestedHaveBitfieldRequestPieceCancelPortKeepAlive"

var _MType_index = [...]uint8{0, 5, 12, 22, 35, 39, 47, 54, 59, 65, 69, 78}

func (i MType) String() string {
	if i >= MType(len(_MType_index)-1) {
		return "MType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MType_name[_MType_index[i]:_MType_index[i+1]]
}
